// Time-of-day greeting + a big pool of short, warm sub-lines that rotate.

export function timeGreeting(d = new Date()): string {
  const h = d.getHours()
  if (h < 5) return 'Still up'
  if (h < 12) return 'Good morning'
  if (h < 17) return 'Good afternoon'
  if (h < 21) return 'Good evening'
  return 'Good night'
}

// 100+ MAIN greetings (the big line). `{name}` is filled in if the user set a
// name, otherwise it's dropped cleanly (see fillName). These rotate so it feels
// fresh every time — like a new-chat greeting — not just the time of day.
export const GREETING_MAIN: string[] = [
  'Welcome back, {name}',
  'Good to see you, {name}',
  'Hey {name}',
  'Hello again, {name}',
  'Ready when you are, {name}',
  "Let's get to it, {name}",
  'Back at it, {name}',
  'There you are, {name}',
  "Let's make today count, {name}",
  'Welcome home, {name}',
  'Hey there, {name}',
  'Nice to see you, {name}',
  "Let's begin, {name}",
  'Good to have you back, {name}',
  "What's the plan, {name}?",
  "Let's do this, {name}",
  "Glad you're here, {name}",
  'Howdy, {name}',
  'Welcome, {name}',
  "Let's make something, {name}",
  'Right on time, {name}',
  'Ready to roll, {name}?',
  "Let's focus, {name}",
  'Take a breath, {name}',
  'Here we go, {name}',
  "Let's pick up where you left off, {name}",
  'Good to have you, {name}',
  'Settle in, {name}',
  "Let's make it a good one, {name}",
  'Hello, {name}',
  'The desk is yours, {name}',
  "Let's get started, {name}",
  'Welcome back to your space, {name}',
  'Ready for today, {name}?',
  "Let's make progress, {name}",
  'Hey again, {name}',
  'Time to shine, {name}',
  "Let's keep it moving, {name}",
  'Good to go, {name}?',
  "You're back, {name}",
  "Let's dive in, {name}",
  'Make yourself at home, {name}',
  "Let's create, {name}",
  'Onward, {name}',
  "Let's build something, {name}",
  'Fresh start, {name}',
  "Let's make today yours, {name}",
  'Hey friend, {name}',
  "Let's get focused, {name}",
  'Your move, {name}',
  "Let's make it happen, {name}",
  'Welcome aboard, {name}',
  "Let's roll, {name}",
  'Glad you made it, {name}',
  "Let's ease in, {name}",
  "The day's yours, {name}",
  "Let's get cracking, {name}",
  'Hey you, {name}',
  'Back in action, {name}',
  "Let's set the tone, {name}",
  'Good to reconnect, {name}',
  "Let's get going, {name}",
  "Today's a canvas, {name}",
  "Let's paint it, {name}",
  'Ready to focus, {name}?',
  "Let's make space, {name}",
  'Welcome to your layer, {name}',
  "You've got this, {name}",
  "Let's start fresh, {name}",
  'A clean slate, {name}',
  "Let's make it count, {name}",
  "Let's win the day, {name}",
  'Step in, {name}',
  "Let's get to work, {name}",
  'Pull up a chair, {name}',
  "Let's make magic, {name}",
  'Good to be back, {name}?',
  "Let's keep building, {name}",
  'The floor is yours, {name}',
  "Let's flow, {name}",
  "Here's to today, {name}",
  "Let's set things in motion, {name}",
  'Welcome in, {name}',
  "Let's chase something good, {name}",
  'Ready to make moves, {name}?',
  "Let's get after it, {name}",
  "You're in the right place, {name}",
  "Let's shape the day, {name}",
  'Good to see you again, {name}',
  'One step at a time, {name}',
  "Hey, let's begin, {name}",
  'Time to create, {name}',
  "Let's make today simple and good, {name}",
  'Welcome back to the canvas, {name}',
  "Let's get into it, {name}",
  "Here whenever you're ready, {name}",
  "Let's make the most of it, {name}",
  'Good to have you around, {name}',
  "Let's start something, {name}",
  'Lovely to see you, {name}',
  'At your service, {name}',
  "Let's keep the momentum, {name}",
  'Easy does it, {name}',
  "Let's tidy up and dive in, {name}",
  'Ready, steady, {name}',
  'The stage is set, {name}',
]

// Fill in the name, or drop the placeholder cleanly when there's no name set.
export function fillName(template: string, name: string): string {
  if (name) return template.replace(/\{name\}/g, name)
  return (
    template
      .replace(/,?\s*\{name\}/g, '')
      .replace(/\s+([?!.])/g, '$1')
      .trim() || 'Welcome back'
  )
}

// 100+ short lines — encouragement, calm, and a little personality. Kept short
// so they read cleanly under the greeting at any widget size.
export const GREETING_LINES: string[] = [
  'Make today count.',
  'One step at a time.',
  'You’ve got this.',
  'Breathe. Begin.',
  'Small steps, big days.',
  'Today is a fresh page.',
  'Do the next right thing.',
  'Progress over perfection.',
  'Keep it simple today.',
  'Be where your feet are.',
  'Start before you’re ready.',
  'Focus on what matters.',
  'Slow is smooth, smooth is fast.',
  'Good things take time.',
  'Show up for yourself.',
  'Little by little adds up.',
  'Make space for what counts.',
  'Choose calm over chaos.',
  'You’re doing better than you think.',
  'Let’s make something good.',
  'Trust the process.',
  'Done is better than perfect.',
  'A calm mind moves mountains.',
  'Stay curious.',
  'Keep going, you’re close.',
  'One thing at a time.',
  'Today, just begin.',
  'Be kind to yourself.',
  'Quiet focus wins.',
  'Tend to today.',
  'Less noise, more signal.',
  'Find your flow.',
  'Make it a little better.',
  'Steady wins.',
  'You set the pace.',
  'Clear the clutter, then create.',
  'Win the morning.',
  'Protect your focus.',
  'Begin with one small thing.',
  'Today is yours to shape.',
  'Keep the streak alive.',
  'Deep breath, then dive in.',
  'Move with intention.',
  'You only need to start.',
  'Build the day you want.',
  'Energy follows focus.',
  'Be present, not perfect.',
  'Plant something today.',
  'A good day starts now.',
  'Make room to think.',
  'Gentle and steady.',
  'Tiny wins are still wins.',
  'Lead with curiosity.',
  'Light work, deep work.',
  'Choose one thing. Do it well.',
  'Calm is a superpower.',
  'You’re allowed to go slow.',
  'Today: a little braver.',
  'Keep your eyes on the next step.',
  'Make today gentle.',
  'Create more than you consume.',
  'Rest is productive too.',
  'Stay soft, stay strong.',
  'Aim small, miss small.',
  'Let today surprise you.',
  'Do less, but better.',
  'Mind like water.',
  'Begin again, as often as needed.',
  'Your pace is the right pace.',
  'Make peace with the to-do list.',
  'Notice something good today.',
  'Keep the main thing the main thing.',
  'Start messy, refine later.',
  'You can do hard things.',
  'Take the small win.',
  'Today rewards showing up.',
  'A clear desk, a clear mind.',
  'Move the needle a little.',
  'Be the calm in the room.',
  'Finish one thing fully.',
  'Let it be easy.',
  'Today is a good day to focus.',
  'Keep it light, keep it moving.',
  'Set the tone early.',
  'You’re exactly where you need to be.',
  'Make today meaningful, not busy.',
  'Trade hustle for focus.',
  'Begin, the rest will follow.',
  'Stack one good hour.',
  'Be patient with the work.',
  'A little progress is enough.',
  'Choose the next small step.',
  'Today: fewer tabs, more focus.',
  'Slow down to speed up.',
  'Make today simple and good.',
  'Care about the little things.',
  'Quiet the noise, hear yourself.',
  'You’ve done hard mornings before.',
  'Keep showing up.',
  'Today counts twice.',
  'One focused hour beats five scattered ones.',
  'Be gentle, be relentless.',
  'Let today be enough.',
  'Start where you are.',
  'Make the next hour great.',
  'Tend the garden of today.',
  'Small and steady, every day.',
  'You set the weather in here.',
  'Pick the rock, not the pebbles.',
  'Today is built one choice at a time.',
]

// A line that stays stable for a while (changes per minute), seeded so it
// doesn't flicker on every render but still feels alive.
export function pickLine(seed: number): string {
  const i = Math.abs(seed) % GREETING_LINES.length
  return GREETING_LINES[i] ?? GREETING_LINES[0] ?? ''
}
